ALTER TABLE "JobPost" ADD COLUMN "isOpen" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "Application"
ADD COLUMN "coverLetter" TEXT NOT NULL DEFAULT '',
ADD COLUMN "resumeUrl" TEXT NOT NULL DEFAULT '',
ADD COLUMN "portfolioUrl" TEXT,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TYPE "ApplicationStatus" ADD VALUE 'REVIEWING';
ALTER TYPE "ApplicationStatus" ADD VALUE 'SHORTLISTED';
ALTER TYPE "ApplicationStatus" ADD VALUE 'WITHDRAWN';